longphamit/kiosk-portal-webapp

- src/@app/configs/locales/en/translation.json
- src/@app/configs/locales/vi/translation.json
- src/@app/services/user_service.ts
- src/@app/utils/http_client.ts
- src/kiosk_portal/pages/account/account_manager.jsx
> Update CPF145 and CPF150

- src/@app/pages/login/login_page.tsx
- src/@app/pages/reset_pass/reset_pass.js
- src/@app/redux/slices/auth_slice.tsx
- src/@app/routers/app-element.tsx
- src/@app/routers/routes.ts
- src/@app/services/user_service.ts
- src/@app/utils/http_client.ts
- Resolved [CPF-137](https://phamlong.atlassian.net/browse/CPF-137)
- The compare password is _**abc@123**_
---
Remaining issues:
- Internalization: validation messages.
- Only admin role active to navigate to the home page ( Location Owner | Service Provider not yet )
> [CPF-137] Force to change password for the 1st login

- src/@app/services/user_service.ts
- src/@app/utils/http_client.ts
- src/kiosk_portal/pages/account/account_manager.jsx
- Resolved [CPF-149](https://phamlong.atlassian.net/browse/CPF-149)
- Search by FirstName, LastName, PhoneNumber, Address, Role, Status.
- 2 types of searching: Search by a specific field and all fields
---
Remaining issues:
- Internalization: validation messages.
> [CPF-149] [AD] Search Accounts 

- src/@app/services/user_service.ts
- src/@app/utils/http_client.ts
- src/kiosk_portal/pages/account/account_manager.jsx
- Resolved [CPF-147](https://phamlong.atlassian.net/browse/CPF-147)
- Editable fields: FirstName, LastName, PhoneNumber, Address, dateOfBirth.
- 2 types of searching: Search by a specific field and all fields
---
Remaining issues:
- Internalization: validation messages.
> [CPF-147] [AD] Update Account

- src/@app/components/authen_layout/index.tsx
- src/@app/pages/login/login_page.tsx
- src/@app/routers/routes.ts
- src/kiosk_portal/pages/application/index.jsx
- src/kiosk_portal/services/application_service.ts
> CPF-192 and CPF-193

- src/@app/utils/date_util.ts
- src/@app/utils/list_select_util.ts
- src/kiosk_portal/components/tables/app_table/index.jsx
- src/kiosk_portal/pages/account/index.jsx
- src/kiosk_portal/pages/schedule/index.jsx
- src/kiosk_portal/services/application_service.ts
- src/kiosk_portal/services/categories_service.ts
- src/kiosk_portal/services/role_service.ts
- src/kiosk_portal/services/schedule_service.ts
update create schedule and create application + load list categories
> update create schedule and create application + load list categories

- src/kiosk_portal/components/tables/app_table/index.jsx
- src/kiosk_portal/services/application_service.ts
> CPF-186 Update Application

- src/@app/components/authen_layout/index.tsx
- src/@app/routers/routes.ts
- src/@app/utils/date_util.ts
- src/kiosk_portal/pages/poi/index.jsx
- src/kiosk_portal/pages/schedule/index.jsx
- src/kiosk_portal/services/map_service.ts
- src/kiosk_portal/services/poi_service.ts
> CPF-231-232

- src/@app/utils/image_util.ts
- src/kiosk_portal/components/tables/app_table/index.jsx
- src/kiosk_portal/pages/app_category/index.jsx
- src/kiosk_portal/pages/app_category/modalCreate.jsx
- src/kiosk_portal/services/categories_service.ts
> CPF-226 Modal Create Category

- src/kiosk_portal/pages/app_category/modalCreate.jsx
- src/kiosk_portal/pages/schedule/index.jsx
- src/kiosk_portal/pages/schedule/modalAddTemplate.jsx
- src/kiosk_portal/pages/template/index.jsx
- src/kiosk_portal/services/schedule_template_service.ts
CPF-180 add template to schedule
> CPF-180 add template to schedule

- src/kiosk_portal/components/tables/app_table/index.jsx
- src/kiosk_portal/pages/application/modalDetailApplication.jsx
CPF-212 Application Detail Page
> CPF-212 Application Detail Page

- package-lock.json
- src/@app/utils/date_util.ts
- src/kiosk_portal/components/tables/app_table/index.jsx
- src/kiosk_portal/pages/poi/index.jsx
- src/kiosk_portal/pages/poi/modalCreatePoi.jsx
- src/kiosk_portal/pages/poi/modalUpdatePoi.jsx
- src/kiosk_portal/services/poi_category_service.ts
> update FE of Update Poi

- src/@app/components/authen_layout/index.tsx
- src/@app/routers/routes.ts
- src/kiosk_portal/pages/poi/index.jsx
- src/kiosk_portal/pages/poi/modalAdvanceSearch.jsx
- src/kiosk_portal/pages/poi/modalUpdatePoi.jsx
- src/kiosk_portal/pages/poi_category/index.jsx
- src/kiosk_portal/pages/poi_category/modalCreatePoiCategory.jsx
- src/kiosk_portal/services/poi_category_service.ts
- src/kiosk_portal/services/poi_service.ts
> Show + Create Poi Category

- src/kiosk_portal/pages/poi/index.jsx
- src/kiosk_portal/pages/poi/modalAdvanceSearch.jsx
- src/kiosk_portal/pages/poi/modalCreatePoi.jsx
- src/kiosk_portal/pages/poi/modalUpdatePoi.jsx
> update create POI

- src/@app/components/authen_layout/index.tsx
- src/@app/routers/routes.ts
- src/kiosk_portal/pages/event/event_details.jsx
- src/kiosk_portal/pages/event/index.jsx
- src/kiosk_portal/services/event_service.ts
- src/kiosk_portal/services/location_services.ts
> [CPF-216] CRUD Event

- src/kiosk_portal/pages/poi/index.jsx
- src/kiosk_portal/pages/poi/modalAdvanceSearch.jsx
- src/kiosk_portal/pages/poi/modalCreatePoi.jsx
> Search POI

- src/kiosk_portal/pages/poi/index.jsx
> finish search POI

- src/@app/pages/login/login_page.tsx
- src/kiosk_portal/pages/account/index.jsx
- src/kiosk_portal/pages/poi/poi_detail.jsx
update login + load list image
> update login + load list image

- src/kiosk_portal/pages/app_category/index.jsx
- src/kiosk_portal/pages/app_category/modalUpdateAppCategory.jsx
- src/kiosk_portal/pages/poi/modalCreatePoi.jsx
- src/kiosk_portal/pages/poi_category/index.jsx
- src/kiosk_portal/pages/poi_category/modalUpdatePoiCategory.jsx
- src/kiosk_portal/services/app_category_service.ts
- src/kiosk_portal/services/poi_category_service.ts
update app category and update poi category
> update app category and update poi category

- src/kiosk_portal/pages/app_category/modalUpdateAppCategory.jsx
- src/kiosk_portal/pages/poi/modalCreatePoi.jsx
- src/kiosk_portal/pages/poi/poi_detail.jsx
- src/kiosk_portal/pages/poi_category/modalUpdatePoiCategory.jsx
- src/kiosk_portal/services/poi_service.ts
update basic information POI and fix bug create POI
> update basic information POI and fix bug create POI

- src/@app/components/authen_layout/index.tsx
- src/@app/routers/routes.ts
- src/kiosk_portal/pages/my_application/index.jsx
- src/kiosk_portal/services/party_service_application.ts
> show list my-app

- src/kiosk_portal/pages/application_market/index.jsx
> finish page

- src/kiosk_portal/components/tables/kiosk_table/index.js
> update CPF 311

- src/kiosk_portal/pages/poi/poi_detail.jsx
- src/kiosk_portal/pages/schedule/index.jsx
remove search schedule + update message poi
> remove search schedule + update message poi

- src/kiosk_portal/components/tables/app_table/index.jsx
> fix bug create application

- src/kiosk_portal/components/tables/app_publish_request_table/index.js
- src/kiosk_portal/components/tables/app_table/index.jsx
- src/kiosk_portal/constants/app_publish_request_status_constant.js
- src/kiosk_portal/services/app_publish_request_service.ts
> update cancel publish req

- src/kiosk_portal/pages/account/index.jsx
- src/kiosk_portal/pages/kiosk_location/locationDetail.jsx
- src/kiosk_portal/pages/profile/index.jsx
- src/kiosk_portal/services/account_service.ts
> fix bug account page

- src/kiosk_portal/pages/app_category/formCreate.jsx
- src/kiosk_portal/pages/app_category/index.jsx
- src/kiosk_portal/pages/app_category/modalUpdateAppCategory.jsx
> fix bug app category

- src/kiosk_portal/components/tables/app_table/index.jsx
- src/kiosk_portal/pages/account/index.jsx
- src/kiosk_portal/pages/event/event_create.jsx
- src/kiosk_portal/pages/event/event_details.jsx
- src/kiosk_portal/pages/kiosk_location/locationDetail.jsx
- src/kiosk_portal/pages/kiosk_location/modalCreateLocation.jsx
- src/kiosk_portal/pages/poi/index.jsx
- src/kiosk_portal/pages/poi/modalCreatePoi.jsx
- src/kiosk_portal/pages/poi/poi_detail.jsx
> update editor + POI

- src/kiosk_portal/components/tables/app_publish_request_table/index.js
- src/kiosk_portal/components/tables/app_table/index.jsx
- src/kiosk_portal/pages/account/index.jsx
- src/kiosk_portal/pages/app_category/index.jsx
- src/kiosk_portal/pages/application_detail/index.jsx
- src/kiosk_portal/pages/event/index.jsx
> fix bug admin

- src/kiosk_portal/pages/schedule/index.jsx
> add checkbox end day

- src/kiosk_portal/pages/schedule/index.jsx
> fix bug code

- src/kiosk_portal/pages/kiosk_location/index.jsx
> search location

- src/@app/constants/message.ts
- src/kiosk_portal/components/tables/app_table/index.jsx
- src/kiosk_portal/pages/app_category/formCreate.jsx
- src/kiosk_portal/pages/schedule/index.jsx
> fix bug 11

- src/kiosk_portal/pages/event/index.jsx
> fix bug event
